name: Build STUNServer for FreeBSD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-freebsd:
    runs-on: freebsd-latest  # 使用 GitHub 官方提供的 FreeBSD 环境[6,8](@ref)
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 安装编译依赖
      - name: Install dependencies
        run: |
          sudo pkg update -y
          sudo pkg install -y gmake gcc openssl boost-libs

      # 3. 编译源码
      - name: Build STUNServer
        run: |
          gmake  # 使用 GNU Make 替代 FreeBSD 默认的 make[4](@ref)
          ls -lh stunserver stunclient

      # 4. 打包产物（针对 FreeBSD 优化）
      - name: Package binaries
        run: |
          mkdir -p artifacts
          cp stunserver stunclient artifacts/
          tar czf stunserver-freebsd.tar.gz -C artifacts .

      # 5. 上传编译产物
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: stunserver-freebsd-bin
          path: stunserver-freebsd.tar.gz
